<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andini Destiarani">
<meta name="dcterms.date" content="2024-01-20">

<title>PENGARUH PERDAGANGAN EKSPOR-IMPOR TERHADAP KINERJA TENAGA LISTRIK DI JAWA TENGAH 2015 - 2020</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PENGARUH PERDAGANGAN EKSPOR-IMPOR TERHADAP KINERJA TENAGA LISTRIK DI JAWA TENGAH 2015 - 2020</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andini Destiarani </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Jawa Tengah, sebagai salah satu provinsi utama di Indonesia, telah menyaksikan pertumbuhan ekonomi yang pesat selama beberapa tahun terakhir. Pertumbuhan ekonomi yang signifikan ini tidak hanya menciptakan peluang investasi dan pembangunan, tetapi juga memberikan dampak langsung terhadap kebutuhan tenaga listrik. Seiring dengan integrasi ekonomi global, aktivitas perdagangan ekspor-impor di Jawa Tengah menjadi faktor kritis yang berpotensi memengaruhi kinerja sektor tenaga listrik di wilayah ini. Pada periode 2015-2020, Jawa Tengah mengalami berbagai dinamika ekonomi dan tantangan, termasuk dampak pandemi COVID-19 pada tahun 2020 yang telah mengubah pola konsumsi, perdagangan internasional, dan kebijakan energi. Oleh karena itu, penelitian ini dilakukan untuk memberikan wawasan mendalam tentang bagaimana aktivitas perdagangan ekspor-impor di Jawa Tengah dapat dioptimalkan untuk meningkatkan kinerja sektor tenaga listrik, serta mengidentifikasi peluang dan tantangan yang muncul dalam konteks ini.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Dalam penelitian ini penulis mengambil objek penelitian dari Badan Pusat Statistik Jawa Tengah. Ruang lingkup penelitian ini terdapat 3 variabel antara lain nilai ekspor provinsi Jawa Tengah, nilai impor Jawa Tengah, dan nilai produksi listrik Jawa Tengah. Data yang digunakan adalah data yang bersifat time series yaitu dalam kurun waktu 2015-2020 Optimalisasi ini akan dipengaruhi oleh tren perdagangan ekspor dan impor Jawa Tengah dari tahun 2015 hingga 2020 dan juga aktivitas perdagangan terhadap kebutuhan tenaga listrik, dengan memperhatikan komoditas yang terlibat dan partner perdagangan utama.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>. Bagaimana Tren Perdagangan Ekspor-Impor Mempengaruhi Keseimbangan Tenaga Listrik di Jawa Tengah? . Apa Dampak Perubahan Pola Konsumsi Energi Terkait dengan Aktivitas Perdagangan Ekspor-Impor?</p>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Berdasarkan latar belakang dan permasalahan yang ada maka tujuan dari penelitian ini adalah Menyelidiki dampak pertumbuhan ekonomi terhadap tenaga listrik di Jawa Tengah selama periode 2015-2020 dan Mengevaluasi tren perdagangan ekspor dan impor di Jawa Tengah untuk memahami dampaknya terhadap keseimbangan dan efisiensi tenaga listrik. Penelitian ini diharapkan memberikan manfaat yaitu Menyediakan informasi yang dapat digunakan untuk merumuskan dan mengevaluasi kebijakan publik di bidang energi dan perdagangan di tingkat provinsi dan Memberikan wawasan kepada pelaku industri dan bisnis mengenai tren perdagangan dan konsumsi tenaga listrik, memungkinkan mereka untuk mengambil keputusan yang lebih baik.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan sebagai penunjang regresi multivariat dalam penelitian ini antara lain sebagai berikut:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<ol type="1">
<li><p>Ekspor Ekspor merupakan perdagangan dengan cara mengeluarkan atau mengirimkan barang dari dalam wilayah atau keluar wilayah suatu negara (Mey, 2018). Aktivitas ekspor memiliki peran penting dalam perekonomian suatu negara, karena tidak hanya menciptakan pendapatan bagi eksportir, tetapi juga memengaruhi pertumbuhan ekonomi dan penciptaan lapangan kerja. Ekspor dapat menjadi salah satu penggerak pertumbuhan ekonomi. Negara yang aktif dalam kegiatan ekspor cenderung mengalami pertumbuhan ekonomi yang lebih tinggi karena meningkatnya permintaan terhadap produk dan jasa nasional.</p></li>
<li><p>Impor Impor merupakan suatu kegiatan pembelian dan memasukkan barang/ jasa atau komoditas dari luar negeri ke dalam negeri secara legal melalui proses perdagangan (Bea Cukai , 2022). Aktivitas impor memainkan peran penting dalam perdagangan internasional dan membentuk bagian integral dari ekonomi global. Aktivitas impor dapat memiliki dampak yang signifikan pada ekonomi suatu negara. Dengan membawa barang atau jasa dari luar negeri, impor dapat memengaruhi saldo perdagangan, tingkat lapangan kerja, dan kestabilan harga di pasar dalam negeri. Impor memainkan peran kunci dalam membangun konektivitas ekonomi global. Negara-negara saling bergantung satu sama lain untuk memenuhi kebutuhan dan menciptakan saling ketergantungan dalam perdagangan internasional.</p></li>
<li><p>Konsumsi Energi Konsumsi energi adalah penggunaan energi dalam berbagai bentuk oleh suatu masyarakat atau negara. Ini mencakup penggunaan energi listrik, energi panas, bahan bakar transportasi, dan energi lainnya untuk mendukung kegiatan ekonomi, industri, dan kehidupan sehari-hari. Konsumsi energi dapat diukur dalam satuan seperti kilowatt-hour (kWh) atau ton minyak setara (TOE).</p></li>
</ol>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah data yang digunakan sebagai objek penelitian, data dibawah ini merupakan data nilai ekspor, impor, dan tenaga listrik Provinsi Jawa Tengah .</p>
<table class="table">
<caption>Penelitian ini menggunakan data sekunder dengan bentuk data time series 2015-2020, data yang dipakai ialah data yang telah diolah dengan sumber Badan Pusat Statistik Jawa Tengah.</caption>
<thead>
<tr class="header">
<th>Tahun</th>
<th>Ekspor (X)</th>
<th>Impor(S)</th>
<th>Tenaga Listrik (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2015</td>
<td>5374.69</td>
<td>10744.35</td>
<td>25690.27</td>
</tr>
<tr class="even">
<td>2017</td>
<td>447.47</td>
<td>10658.25</td>
<td>39579.73</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>6588.01</td>
<td>14778.86</td>
<td>40798.65</td>
</tr>
<tr class="even">
<td>2019</td>
<td>8516.70</td>
<td>12567.62</td>
<td>42131.61</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>8088.30</td>
<td>8719.80</td>
<td>41715.18</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/luhun"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>andini<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'latihan1.xlsx'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X<span class="sc">+</span>S,<span class="at">data=</span>andini)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>andini<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(andini<span class="sc">$</span>X,andini<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Nilai Ekspor"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>: Plot pengaruh error terhadap Nilai Ekspor</p>
<p><img src="eror.png" class="img-fluid"></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>andini<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(andini<span class="sc">$</span>Y,andini<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Nilai Tenaga Listrik"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Plot pengaruh error terhadap Nilai Tenaga Listrik</p>
<p><img src="Nilai%20Tenaga.png" class="img-fluid"></p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Teknik analisis yang digunakan dalam penelitian ini adalah teknik kuantitatif deskriptif. Metode yang dipilih adalah regresi multivariat dengan 2 variabel independen yaitu ekspor dan impor dan 1 variabel dependen yaitu Tenaga Listrik. Penelitian ini bertujuan untuk mencari hubungan antara ekspor (X) dan impor (S) dengan tenaga listrik (Y). Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 X+ \beta_2 S + \mu
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah hwy dan <span class="math inline">\(x_t\)</span> adalah cty. Di mana Y adalah Tenaga Listrik Jawa Tengah dan X adalah nilai ekspor Jawa Tengah dan S adalah nilai impor Jawa Tengah.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Variabel</th>
<th>Coefficient</th>
<th>Std.Error</th>
<th>t.value</th>
<th>Prob(.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>3.035e+04</td>
<td>2.481e+04</td>
<td>1.223</td>
<td>0.346</td>
</tr>
<tr class="even">
<td>X</td>
<td>4.015e-01</td>
<td>1.476e+00</td>
<td>0.272</td>
<td>0.811</td>
</tr>
<tr class="odd">
<td>R squared</td>
<td>0.06587</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjusted R-Square</td>
<td>-0.8683</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>F-Statistic</td>
<td>0.06587</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Prob(F-statistic)</td>
<td>0.07051</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Hasil regresi yang telah didapat dimasukan ke dalam rumus persamaan yang ada sehingga menjadi:</p>
<p><span class="math display">\[
Y =3.035 +4.016X+ (4.615S)
\]</span></p>
<p>Ekspor pada pertumbuhan ekonomi berperan dalam peningkatan pertumbuhan ekonomi pada Tenaga Listrik dikarenakan nilai variabel X yang positif, tetapi jika dilihat pada hasil regresinya ekspor tidak sepenuhnya mempengaruhi Tenaga Listrik di Jawa Tengah atau dalam arti lain peningkatan Tenaga Listrik bukan hanya dipengaruhi ekspor saja tetapi terdapat faktor lain. Impor pada pertumbuhan ekonomi berbanding terbalik dengan ekspor, impor berpengaruh negatif terhadap Tenaga Listrik Jawa Tengah dikarenakan nilainya yang negatif, tetapi impor juga tidak sepenuhnya mempengaruhi Tenaga Listrik. Jika diasumsikan setiap kenaikan nilai ekspor 1, maka Tenaga Listrik akan meningkat sebesar 4.016. Tetapi jika diasumsikan nilai impor 1, maka Tenaga Listrik akan ada penurunan sebesar 4.614.</p>
<p>Nilai F-statistik sebesar 0.06587 menunjukkan bahwa variabel independen dalam jangka panjang seperti ekspor, impor berpengaruh secara bersama-sama terhadap tingkat pertumbuhan ekonomi atau terhadap Tenaga Listrik.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah :</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>andini<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'latihan1.xlsx'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X<span class="sc">+</span>S,<span class="at">data=</span>andini)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Hasil%20Regresi.png" class="img-fluid"></p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan hasil regresi multivariat yang dilakukan, terdapat beberapa kesimpulan yang dapat diambil: 1. Variabel ekspor (X) memiliki pengaruh positif terhadap pertumbuhan ekonomi atau peningkatan tenaga listrik di Jawa Tengah. Namun, pengaruhnya tidak sepenuhnya dominan, karena terdapat faktor lain yang juga mempengaruhi peningkatan tenaga listrik.</p>
<ol start="2" type="1">
<li><p>Variabel impor (S) memiliki pengaruh negatif terhadap pertumbuhan ekonomi atau peningkatan tenaga listrik di Jawa Tengah. Jika nilai impor meningkat sebesar 1, maka tenaga listrik akan mengalami penurunan sebesar 4.614.</p></li>
<li><p>Hasil analisis menunjukkan bahwa variabel independen, yaitu ekspor dan impor, secara bersama-sama berpengaruh terhadap tingkat pertumbuhan ekonomi atau peningkatan tenaga listrik di Jawa Tengah.</p></li>
<li><p>Koefisien determinasi (R-squared) sebesar 0.06587 menunjukkan bahwa model regresi yang digunakan hanya mampu menjelaskan sekitar 6.587% variasi dalam data. Hal ini menunjukkan bahwa terdapat faktor lain yang tidak dimasukkan dalam model yang juga mempengaruhi pertumbuhan ekonomi atau peningkatan tenaga listrik.</p></li>
<li><p>Dalam analisis masalah, dilakukan pengolahan data menggunakan library “readxl” dan dilakukan regresi menggunakan fungsi “lm” pada data yang telah diolah. Hasil regresi tersebut digunakan untuk membuat plot pengaruh error terhadap nilai ekspor dan nilai tenaga listrik.</p></li>
</ol>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p><em>Bea Cukai . (2022). IMPOR. Retrieved from bcyogyakarta.beacukai.go.id: https://bcyogyakarta.beacukai.go.id/impor.html</em></p>
<p><em>Mey, R. (2018). Ekspor dan Impor. Sleman: Politeknik Banjarmasin.</em></p>
<p><em>Pengertian Ekspor�|�hestanto. (n.d.). Retrieved January 19, 2023, from <a href="https://www.hestanto.web.id/ekspor/" class="uri">https://www.hestanto.web.id/ekspor/</a></em></p>
<p><em>Multivariat &amp; Dummy regression. (n.d.). Retrieved January 19, 2023, from <a href="https://www.krisna.or.id/metopel/meeting3/index.html#/bandingkan-2-model" class="uri">https://www.krisna.or.id/metopel/meeting3/index.html#/bandingkan-2-model</a></em></p>
<p><em>BPS Provinsi Jawa Tengah. (n.d). Retrieved January 19, 2024, from https://jateng.bps.go.id/indicator/8/52/1/nilai-ekspor-dan-impor.html</em></p>
<p>BPS Provinsi Jawa Tengah. (n.d). Retrieved January 19, 2024, from https://jateng.bps.go.id/publication/2022/11/15/acef47b91df2e0c3d69f0e49/statistik-listrik- provinsi-jawa-tengah-2020.html</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>